# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'translate-live' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for translate-live
  pod 'AudioKit', '~> 4.0'

end
