name: "Build hex2rgb"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - 
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - run: php netlify/hex2rgb/generate.php
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.HEX2RGB_NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.HEX2RGB_NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: '/tmp/hex2rgb/output'
