name: "Build webmention-cli"
on:
  pull_request:
  push:
jobs:
  build:
    defaults:
       run:
        shell: bash
        working-directory: rust/webmention-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v10
      name: Install nix
    - run: make deploy-action
