name: "Build webmention-cli"
defaults:
  run:
    shell: bash
    working-directory: rust/webmention-cli
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v10
        name: Install nix
      - name: Build package
        working-directory: ./rust/webmention-cli
        run: |
          pwd
          ls
          make build
