name: "Build webmention-cli"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Install packages
        run: apt update && apt install libssl-dev
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v10
        name: Install nix
      - name: Build package
        working-directory: ./rust/webmention-cli
        run: make build
